events {}
http {
  access_log off;
  server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate /qa-certs/cert.pem;
    ssl_certificate_key /qa-certs/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    location /api/ {
      proxy_pass http://backend:4002;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $remote_addr;
    }
    location / {
      proxy_pass http://frontend:3000;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
